version: '3.8'

services:
  db:
    container_name: agenda-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: agenda-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - agenda-volume:/var/lib/postgresql/data

volumes:
  agenda-volume:
