version: '3.8'

services:
  db:
    container_name: agenda-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: agenda-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - agenda-network

  pgadmin:
    container_name: agenda-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "15432:80"
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge
